version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./config/development.env
  frontend:
    image: "marketplace-frontend-dev"
    build: ./marketplace-for-handmade-client
    ports:
      - "3000:3000"
    volumes:
      - ./marketplace-for-handmade-client/src:/app/src
  backend:
    image: "marketplace-backend-dev"
    build:
      context: ./marketplace-for-handmade-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./marketplace-for-handmade-server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./config/development.env
volumes:
  mongo-data: